# 导航目录
menu:
  主页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  收藏||fas fa-list:
    音乐: /music/ || fas fa-music
    视频: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# 代码框
highlight_theme: light # 代码框样式
highlight_copy: true # 复制按钮
highlight_lang: true # 显示代码语法
highlight_shrink: false  # 收缩代码块/展开代码块/展开代码块并隐藏按钮：true/false/none 
highlight_height_limit: 200 # 代码框高度限制 unit: px
code_word_wrap: false # 文本换行

# 复制
copy:
  enable: true
  copyright:	# 复制的后面加版权信息
    enable: false
    limit_count: 50

# 社交&图标
social:
  fab fa-github: https://github.com/wangmin-1995 || Github
  fas fa-envelope: mailto:wangmin-1995@outlook.com || Email

# 站内搜索

# Algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6

# Local search
local_search:
  enable: true
  preload: false	# 预装
  CDN:

# Math (數學)---不修改
# --------------------------------------
# About the per_page
# if you set it to true, it will load mathjax/katex script in each page (true 表示每一頁都加載js)
# if you set it to false, it will load mathjax/katex script according to your setting (add the 'mathjax: true' in page's front-matter)
# (false 需要時加載，須在使用的 Markdown Front-matter 加上 mathjax: true)

# MathJax
mathjax:
  enable: false
  per_page: false

# KaTeX
katex:
  enable: false
  per_page: false
  hide_scrollbar: true

# 图标&图片

# 网站图标
favicon: /img/favicon.png

# 头像
avatar:
  img: https://s2.loli.net/2022/06/26/GB9iaNPwlk4U1ho.jpg
  effect: false	# true：头像会一直转

# Disable all banner image
disable_top_img: false

# The banner image of home page
index_img:

# 默认的top_img，当页面的top_img没有配置时，会显示default_top_img
default_top_img: https://s2.loli.net/2022/05/06/MF6cDtkeNGTZbE1.jpg

# The banner image of archive page
archive_img:

# If the banner of tag page not setting, it will show the top_img
# note: tag page, not tags page (子標籤頁面的 top_img)
tag_img:

# The banner image of tag page
# format:
#  - tag name: xxxxx
tag_per_img:

# If the banner of category page not setting, it will show the top_img
# note: category page, not categories page (子分類頁面的 top_img)
category_img:

# The banner image of category page
# format:
#  - category name: xxxxx
category_per_img:

cover:
  index_enable: true  # 是否显示文章封面
  aside_enable: true
  archives_enable: true
  position: both  # 封面显示的位置：left/right/both
  default_cover:	# 没有设置Front_matter时，默认显示的封面，可设置多个
    - https://s2.loli.net/2022/05/06/MF6cDtkeNGTZbE1.jpg

# Replace Broken Images (替換無法顯示的圖片)
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

# A simple 404 page
error_404:
  enable: false
  subtitle: 'Page Not Found'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

# 主页封面信息
post_meta:
  page: # 主页
    date_type: both
    # 主页文章日期是创建日/更新日/都显示：created/updated/both
    date_format: date # 日期/相对日期：date/relative
    categories: true # 主页是否显示分类：true/false
    tags: true # 主页是否显示标签
    label: true # 主页是否显示描述
  post:	# 文章
    date_type: both # created/updated/both
    date_format: date # date/relative
    categories: true # true/false
    tags: true
    label: true

# 字数统计
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# 文章摘录
index_post_content:
  method: 1	# 仅描述/优先描述/自动节选/不显示：1/2/3/false
  length: 500	# 节选范围

# 文章锚点
anchor: true	# 阅读文章时上下拖动，地址栏会根据当前位置的标题而变化

# 目录
toc:
  post: true	# 在文章中显示
  page: false	# 不在标签、分类等页面中显示
  number: true	# 小标题加序号
  expand: true	# 一直展开
  style_simple: false # 侧边栏只显示目录，仅对文章页有效

# 版权信息
post_copyright:	
  enable: true	# 文章底部的版权信息框
  decode: true	# 显示中文网址
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 捐助
reward:
  enable: true
  QR_code:
    - img: /img/wechat.jpg
      link:
      text: wechat
    - img: /img/alipay.jpg
      link:
      text: alipay

# 在线编辑
post_edit:
  enable: true
  # For example: https://github.com/jerryc127/butterfly.js.org/edit/main/source/
  # 需要将本地仓库上传到Github仓库
  url: https://github.com/wangmin-1995/wangmin-1995.github.io/edit/hexo/source/

# 相似文章
related_post:
  enable: true
  limit: 6 # 显示文章的数量
  date_type: created # 创建日/更新日：created/updated

# 图片描述文字
photofigcaption: false

# 底部分页
post_pagination: 2  # 下篇为旧文/下篇为新文/关闭：1/2/false

# 文章过期提醒
noticeOutdate:
  enable: false
  style: flat # 样式: simple/flat
  limit_day: 500 # 期限天数
  position: top # 位置: top/bottom
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# Share System (分享功能)
# --------------------------------------

# AddThis
# https://www.addthis.com/
addThis:
  enable: false
  pubid:

# Share.js
# https://github.com/overtrue/share.js
sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq

# AddToAny
# https://www.addtoany.com/
addtoany:
  enable: false
  item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link

# Comments System
# --------------------------------------

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo/Giscus/Remark42
  use: # Valine,Disqus
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: false # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page

# disqus
# https://disqus.com/
disqus:
  shortname:
  apikey: # For newest comments widget

# Alternative Disqus - Render comments with Disqus API
# DisqusJS 評論系統，可以實現在網路審查地區載入 Disqus 評論列表，兼容原版
# https://github.com/SukkaW/DisqusJS
disqusjs:
  shortname:
  apikey:
  option:

# livere (來必力)
# https://www.livere.com/
livere:
  uid:

# gitalk
# https://github.com/gitalk/gitalk
gitalk:
  client_id:
  client_secret:
  repo:
  owner:
  admin:
  option:

# valine
# https://valine.js.org
valine:
  appId: # leancloud application app id
  appKey: # leancloud application app key
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  bg: # valine background
  visitor: false
  option:

# waline - A simple comment system with backend support fork from Valine
# https://waline.js.org/
waline:
  serverURL: # Waline server address url
  bg: # waline background
  pageview: false
  option:

# utterances
# https://utteranc.es/
utterances:
  repo:
  # Issue Mapping: pathname/url/title/og:title
  issue_term: pathname
  # Theme: github-light/github-dark/github-dark-orange/icy-dark/dark-blue/photon-dark
  light_theme: github-light
  dark_theme: photon-dark

# Facebook Comments Plugin
# https://developers.facebook.com/docs/plugins/comments/
facebook_comments:
  app_id:
  user_id: # optional
  pageSize: 10 # The number of comments to show
  order_by: social # social/time/reverse_time
  lang: en_US # Language en_US/zh_CN/zh_TW and so on

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId:
  region:
  visitor: false
  option:

# Giscus
# https://giscus.app/
giscus:
  repo:
  repo_id:
  category_id:
  theme:
    light: light
    dark: dark
  option:

# Remark42
# https://remark42.com/docs/configuration/frontend/
remark42:
  host: # Your Host URL
  siteId: # Your Site ID
  option:

# Chat Services
# --------------------------------------

# Chat Button [recommend]
# It will create a button in the bottom right corner of website, and hide the origin button
chat_btn: false

# The origin chat button is displayed when scrolling up, and the button is hidden when scrolling down
chat_hide_show: false

# chatra
# https://chatra.io/
chatra:
  enable: false
  id:

# tidio
# https://www.tidio.com/
tidio:
  enable: false
  public_key:

# daovoice
# http://daovoice.io/
daovoice:
  enable: false
  app_id:

# gitter
# https://gitter.im/
gitter:
  enable: false
  room:

# crisp
# https://crisp.chat/en/
crisp:
  enable: false
  website_id:

# 页脚
footer:
  owner:
    enable: true
    since: 2022
  custom_text:
  copyright: true # 主题和框架的著作权

# Analysis
# --------------------------------------

# Baidu Analytics
# https://tongji.baidu.com/web/welcome/login
baidu_analytics:

# Google Analytics
# https://analytics.google.com/analytics/web/
google_analytics:

# CNZZ Analytics
# https://www.umeng.com/
cnzz_analytics:

# Cloudflare Analytics
# https://www.cloudflare.com/zh-tw/web-analytics/
cloudflare_analytics:

# Microsoft Clarity
# https://clarity.microsoft.com/
microsoft_clarity:

# Advertisement
# --------------------------------------

# Google Adsense (谷歌廣告)
google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client:
  enable_page_level_ads: true

# Insert ads manually (手動插入廣告)
# ad:
#   index:
#   aside:
#   post:

# Verification (站長驗證)
# --------------------------------------

site_verification:
  # - name: google-site-verification
  #   content: xxxxxx
  # - name: baidu-site-verification
  #   content: xxxxxxx

# Beautify/Effect (美化/效果)
# --------------------------------------

# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!

theme_color:
  enable: true
  main: "#778899"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
  scrollbar_color: "#49b1f5"
  meta_theme_color_light: "ffffff"
  meta_theme_color_dark: "#0d0d0d"

# The top_img settings of home page
# default: top img - full screen, site info - middle (默認top_img全屏，site_info在中間)
# The position of site info, eg: 300px/300em/300rem/10% (主頁標題距離頂部距離)
index_site_info_top:
# The height of top_img, eg: 300px/300em/300rem (主頁top_img高度)
index_top_img_height:

# The user interface setting of category and tag page (category和tag頁的UI設置)
# index - same as Homepage UI (index 值代表 UI將與首頁的UI一樣)
# default - same as archives UI 默認跟archives頁面UI一樣
category_ui: # 留空或 index
tag_ui: # 留空或 index

# 网站背景
background: "#778899"	# 亮岩灰，图片或颜色，颜色代码：https://encycolorpedia.cn/

# 底部背景
footer_bg: false	# true：顶部图延伸

# the position of bottom right button/default unit: px (右下角按鈕距離底部的距離/默認單位為px)
rightside-bottom:

# 进入效果
enter_transitions: true

# Background effects (背景特效)
# --------------------------------------

# canvas_ribbon (靜止彩帶背景)
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false

# 动态彩带
canvas_fluttering_ribbon:	# 动态彩带
  enable: true
  mobile: true	# 适用手机

# canvas_nest
# https://github.com/hustcc/canvas-nest.js
canvas_nest:
  enable: false
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false

# 打字效果
activate_power_mode:
  enable: true
  colorful: true # 冒光特效
  shake: true # 抖动特效
  mobile: true

# Mouse click effects: fireworks (鼠標點擊效果: 煙火特效)
fireworks:
  enable: false
  zIndex: 9999 # -1 or 9999
  mobile: false

# Mouse click effects: Heart symbol (鼠標點擊效果: 愛心)
click_heart:
  enable: false
  mobile: false

# 鼠标点击效果: 文字
ClickShowText:	# 鼠标点击文字
  enable: true
  text:
    - 回归
    - 纯净
    - 自己
  fontSize: 15px
  random: false	# 随机
  mobile: true	# 手机

# Default display mode (網站默認的顯示模式)
# light (default) / dark
display_mode: light

# 文章小标题前图标
beautify:
  enable: true
  field: post # site/post
  title-prefix-icon: # '\f0c1'
  title-prefix-icon-color: # '#F47466'

# 全局字体
font:
  global-font-size:
  code-font-size:
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  code-font-family: consolas, Menlo, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif

# 网站标题字体
blog_title_font:	# 左上角网站名，主页居中网站名
  font_link: https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
  font-family: Titillium Web, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif

# 水平分隔线
hr_icon:
  enable: true
  icon: # 字体图标的unicode值，例如“\ 3423”
  icon-top:

# 主页副标题
subtitle:
  enable: true
  effect: true	# 打字效果
  loop: true	# 循环打字
  source: 3	# 一言网/一句网/今日诗词/关闭：1/2/3/false
  sub:	# source设置false：只显示sub第一行文字

# 加载动画
preloader: true

# 侧边栏
aside:
  enable: true
  hide: false   # 隐藏
  button: true  # 设置按钮
  mobile: true # 手机上显示
  position: right # 左或右
  display:  # 显示归档、标签、分类数量
    archive: true
    tag: true
    category: true
  card_author:  # 显示站长卡片
    enable: true
    description: 我是站长    # 描述
    button: # 站长Github链接
      enable: true
      icon: fab fa-github
      text: Follow Me！
      link: https://github.com/wangmin-1995
  card_announcement:    # 公告
    enable: true
    content: 欢迎来到Minge的博客！
  card_recent_post: # 最近文章
    enable: true
    limit: 0 # 0为显示全部
    sort: updated # date/updated
    sort_order: # 轻易不修改
  card_categories:
    enable: true
    limit: 0 # 设置为0全部显示
    expand: true # 展开：none/true/false
    sort_order: # 轻易不修改
  card_tags: 
    enable: true
    limit: 0 # 设置为0全部显示
    color: true # 不同颜色
    sort_order: # 轻易不修改
  card_archives:
    enable: true
    type: monthly # yearly/monthly
    format: MMMM YYYY # 例: YYYY年MM月
    order: -1 # 升序/降序：1/-1
    limit: 0 # 设置为0全部显示
    sort_order: # 轻易不修改
  card_webinfo: # 网站信息卡片
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # 轻易不修改

# 访问人数
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 网页运行时间
runtimeshow:
  enable: true
  publish_date: 2/22/2022 22:22:22

# 最新评论
newest_comments:
  enable: false
  sort_order: # 轻易不修改
  limit: 6
  storage: 10 # 单位:分钟,将数据保存到本地文件
  avatar: true

# 繁简转换
translate:
  enable: true
  default: 繁
  defaultEncoding: 2	# 繁/简：1/2
  translateDelay: 0	# 延时
  msgToTraditionalChinese: '繁'
  msgToSimplifiedChinese: '簡'

# 阅读模式
readmode: true

# 夜晚模式
darkmode:
  enable: true
  button: true
  autoChangeMode: 3 # 根据系统自动切换/下午6点至上午6点/关闭：1/2/false

# 按钮顺序
rightside_item_order:
  enable: false
  hide: # readmode,translate,darkmode,hideAside
  show: # toc,chat,comment

# 大图查看模式
medium_zoom: false	# 2选1
fancybox: true

# 标签外挂
# mermaid
mermaid:
  enable: false
  theme:
    light: default
    dark: dark

# Note (Bootstrap Callout)
note:
  style: flat	# simple/modern/flat/desabled
  icons: true
  border_radius: 3
  light_bg_offset: 0

# other
# --------------------------------------

# Pjax
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
  enable: false
  exclude:
    # - xxxx
    # - xxxx

# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: false
  per_page: true

# 弹窗
snackbar:
  enable: false
  position: bottom-left # top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
  bg_light: '#49b1f5' # 亮主题下
  bg_dark: '#1f1f1f' # 暗主题下

# https://instant.page/
# prefetch (預加載)
instantpage: false

# 中英文之間添加空格
pangu:
  enable: true
  field: site # site/post

# 图片懒加载
lazyload:
  enable: false
  field: site # site/post
  placeholder:
  blur: false

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
# pwa:
#   enable: false
#   manifest: /pwa/manifest.json
#   apple_touch_icon: /pwa/apple-touch-icon.png
#   favicon_32_32: /pwa/32.png
#   favicon_16_16: /pwa/16.png
#   mask_icon: /pwa/safari-pinned-tab.svg

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta: true

# Add the vendor prefixes to ensure compatibility
css_prefix: true

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>

# CDN
# Don't modify the following settings unless you know how they work
# 非必要請不要修改
CDN:
  # The CDN provider of internal scripts (主題內部 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( dev版的主題只能設置為 local )
  internal_provider: local

  # The CDN provider of third party scripts (第三方 js 的 cdn 配置)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # when set it to local, you need to install hexo-butterfly-extjs
  third_party_provider: jsdelivr

  # Add version number to CDN, true or false  
  version: false

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format:

  option:
    # main_css:
    # main:
    # utils:
    # translate:
    # local_search:
    # algolia_js:
    # algolia_search_v4:
    # instantsearch_v4:
    # pjax:
    # gitalk:
    # gitalk_css:
    # blueimp_md5:
    # valine:
    # disqusjs:
    # disqusjs_css:
    # twikoo:
    # waline_js:
    # waline_css:
    # sharejs:
    # sharejs_css:
    # mathjax:
    # katex:
    # katex_copytex:
    # mermaid:
    # canvas_ribbon:
    # canvas_fluttering_ribbon:
    # canvas_nest:
    # lazyload:
    # instantpage:
    # typed:
    # pangu:
    # fancybox_css_v4:
    # fancybox_v4:
    # medium_zoom:
    # snackbar_css:
    # snackbar:
    # activate_power_mode:
    # fireworks:
    # click_heart:
    # ClickShowText:
    # fontawesomeV6:
    # flickr_justified_gallery_js:
    # flickr_justified_gallery_css:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # prismjs_js:
    # prismjs_lineNumber_js:
    # prismjs_autoloader: